from smolagents import ToolCollection, CodeAgent
from smolagents import OpenAIServerModel
from smolagents import PromptTemplates
import os

model = OpenAIServerModel(
    model_id = "deepseek-chat", 
    api_base ="https://api.deepseek.com/v1",
    api_key=os.environ["DEEPSEEK_API_KEY"],
)

SYS_PROMPT="""
Review the current state of the page and all other information to find the best
possible next action to accomplish your goal. 
"""

FIRST_PAGE ="""
# Current page Accessibility Tree

RootWebArea 'Dashboard / Magento Admin', focused
	[148] link 'Magento Admin Panel'
		[149] image 'Magento Admin Panel'
	[150] navigation ''
		[151] menubar '', orientation='horizontal'
			[153] link '\ue604 DASHBOARD'
				StaticText '\ue604'
				StaticText 'DASHBOARD'
			[156] link '\ue60b SALES'
				StaticText '\ue60b'
				StaticText 'SALES'
			[189] link '\ue608 CATALOG'
				StaticText '\ue608'
				StaticText 'CATALOG'
			[207] link '\ue603 CUSTOMERS'
				StaticText '\ue603'
				StaticText 'CUSTOMERS'
			[226] link '\ue609 MARKETING'
				StaticText '\ue609'
				StaticText 'MARKETING'
			[293] link '\ue602 CONTENT'
				StaticText '\ue602'
				StaticText 'CONTENT'
			[339] link '\ue60a REPORTS'
				StaticText '\ue60a'
				StaticText 'REPORTS'
			[464] link '\ue60d STORES'
				StaticText '\ue60d'
				StaticText 'STORES'
			[540] link '\ue610 SYSTEM'
				StaticText '\ue610'
				StaticText 'SYSTEM'
			[623] link '\ue612 FIND PARTNERS & EXTENSIONS'
				StaticText '\ue612'
				StaticText 'FIND PARTNERS & EXTENSIONS'
	[653] banner ''
		[656] heading 'Dashboard'
		[659] link '\ue600 admin'
			StaticText '\ue600'
			StaticText 'admin'
		[671] link '\ue607'
			StaticText '\ue607'
		[673] Section ''
			[675] LabelText ''
				StaticText '\ue60c'
			[679] textbox '\ue60c'
	[685] main ''
		StaticText 'Scope:'
		[696] button 'All Store Views', hasPopup='menu'
		[707] link '\ue633 What is this?'
			StaticText '\ue633'
			StaticText 'What is this?'
		[712] Section ''
			[714] button 'Reload Data'
		[718] Section ''
			StaticText 'Advanced Reporting'
			StaticText "Gain new insights and take command of your business' performance, using our dynamic product, order, and customer reports tailored to your customer data."
			[723] link 'Go to Advanced Reporting \ue644'
				StaticText 'Go to Advanced Reporting'
				StaticText '\ue644'
		StaticText 'Chart is disabled. To enable the chart, click'
		[730] link 'here'
		StaticText '.'
		[733] list ''
			[734] listitem ''
				StaticText 'Revenue'
				[736] strong ''
					StaticText '$0.00'
			[739] listitem ''
				StaticText 'Tax'
				[741] strong ''
					StaticText '$0.00'
			[744] listitem ''
				StaticText 'Shipping'
				[746] strong ''
					StaticText '$0.00'
			[749] listitem ''
				StaticText 'Quantity'
				[751] strong ''
					StaticText '0'
		[755] tablist '', multiselectable=False, orientation='horizontal'
			[756] tab 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... Bestsellers', expanded=True, selected=True, controls='grid_tab_ordered_products_content'
				[757] link 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... Bestsellers'
					StaticText 'Bestsellers'
			[763] tab 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... Most Viewed Products', expanded=False, selected=False, controls='ui-id-1'
				[764] link 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... Most Viewed Products'
					StaticText 'Most Viewed Products'
			[771] tab 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... New Customers', expanded=False, selected=False, controls='ui-id-2'
				[772] link 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... New Customers'
					StaticText 'New Customers'
			[779] tab 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... Customers', expanded=False, selected=False, controls='ui-id-3'
				[780] link 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... Customers'
					StaticText 'Customers'
		[789] tabpanel 'The information in this tab has been changed. This tab contains invalid data. Please resolve this before saving. Loading... Bestsellers'
			[791] table ''
				[792] rowgroup ''
					[793] row ''
						[794] columnheader 'Product'
							StaticText 'Product'
						[796] columnheader 'Price'
							StaticText 'Price'
						[798] columnheader 'Quantity'
							StaticText 'Quantity'
				[800] rowgroup ''
					[801] row 'http://10.7.4.57:9083/admin/catalog/product/edit/id/20/'
						[802] gridcell 'Quest Lumaflex™ Band'
						[803] gridcell '$19.00'
						[804] gridcell '6'
					[805] row 'http://10.7.4.57:9083/admin/catalog/product/edit/id/33/'
						[806] gridcell 'Sprite Yoga Strap 6 foot'
						[807] gridcell '$14.00'
						[808] gridcell '6'
					[809] row 'http://10.7.4.57:9083/admin/catalog/product/edit/id/29/'
						[810] gridcell 'Sprite Stasis Ball 65 cm'
						[811] gridcell '$27.00'
						[812] gridcell '6'
					[813] row 'http://10.7.4.57:9083/admin/catalog/product/edit/id/25/'
						[814] gridcell 'Sprite Stasis Ball 55 cm'
						[815] gridcell '$23.00'
						[816] gridcell '5'
					[817] row 'http://10.7.4.57:9083/admin/catalog/product/edit/id/13/'
						[818] gridcell 'Overnight Duffle'
						[819] gridcell '$45.00'
						[820] gridcell '5'
		StaticText 'Lifetime Sales'
		[828] strong ''
			StaticText '$0.00'
		StaticText 'Average Order'
		[834] strong ''
			StaticText '$0.00'
		StaticText 'Last Orders'
		[840] table ''
			[841] rowgroup ''
				[842] row ''
					[843] columnheader 'Customer'
						StaticText 'Customer'
					[845] columnheader 'Items'
						StaticText 'Items'
					[847] columnheader 'Total'
						StaticText 'Total'
			[849] rowgroup ''
				[850] row 'http://10.7.4.57:9083/admin/sales/order/view/order_id/299/'
					[851] gridcell 'Sarah Miller'
					[852] gridcell '5'
					[853] gridcell '$194.40'
				[854] row 'http://10.7.4.57:9083/admin/sales/order/view/order_id/65/'
					[855] gridcell 'Grace Nguyen'
					[856] gridcell '4'
					[857] gridcell '$190.00'
				[858] row 'http://10.7.4.57:9083/admin/sales/order/view/order_id/125/'
					[859] gridcell 'Matt Baker'
					[860] gridcell '3'
					[861] gridcell '$151.40'
				[862] row 'http://10.7.4.57:9083/admin/sales/order/view/order_id/136/'
					[863] gridcell 'Lily Potter'
					[864] gridcell '4'
					[865] gridcell '$188.20'
				[866] row 'http://10.7.4.57:9083/admin/sales/order/view/order_id/230/'
					[867] gridcell 'Ava Brown'
					[868] gridcell '2'
					[869] gridcell '$83.40'
		StaticText 'Last Search Terms'
		[874] table ''
			[875] rowgroup ''
				[876] row ''
					[877] columnheader 'Search Term'
						StaticText 'Search Term'
					[879] columnheader 'Results'
						StaticText 'Results'
					[881] columnheader 'Uses'
						StaticText 'Uses'
			[883] rowgroup ''
				[884] row 'http://10.7.4.57:9083/admin/search/term/edit/id/25/'
					[885] gridcell 'tanks'
					[886] gridcell '23'
					[887] gridcell '1'
				[888] row 'http://10.7.4.57:9083/admin/search/term/edit/id/19/'
					[889] gridcell 'nike'
					[890] gridcell '0'
					[891] gridcell '3'
				[892] row 'http://10.7.4.57:9083/admin/search/term/edit/id/1/'
					[893] gridcell 'Joust Bag'
					[894] gridcell '10'
					[895] gridcell '4'
				[896] row 'http://10.7.4.57:9083/admin/search/term/edit/id/11/'
					[897] gridcell 'hollister'
					[898] gridcell '1'
					[899] gridcell '19'
				[900] row 'http://10.7.4.57:9083/admin/search/term/edit/id/13/'
					[901] gridcell 'Antonia Racer Tank'
					[902] gridcell '23'
					[903] gridcell '2'
		StaticText 'Top Search Terms'
		[908] table ''
			[909] rowgroup ''
				[910] row ''
					[911] columnheader 'Search Term'
						StaticText 'Search Term'
					[913] columnheader 'Results'
						StaticText 'Results'
					[915] columnheader 'Uses'
						StaticText 'Uses'
			[917] rowgroup ''
				[918] row 'http://10.7.4.57:9083/admin/search/term/edit/id/11/'
					[919] gridcell 'hollister'
					[920] gridcell '1'
					[921] gridcell '19'
				[922] row 'http://10.7.4.57:9083/admin/search/term/edit/id/1/'
					[923] gridcell 'Joust Bag'
					[924] gridcell '10'
					[925] gridcell '4'
				[926] row 'http://10.7.4.57:9083/admin/search/term/edit/id/13/'
					[927] gridcell 'Antonia Racer Tank'
					[928] gridcell '23'
					[929] gridcell '2'
				[930] row 'http://10.7.4.57:9083/admin/search/term/edit/id/25/'
					[931] gridcell 'tanks'
					[932] gridcell '23'
					[933] gridcell '1'
				[934] row 'http://10.7.4.57:9083/admin/search/term/edit/id/9/'
					[935] gridcell 'WP10'
					[936] gridcell '1'
					[937] gridcell '1'
	[939] contentinfo ''
		[942] paragraph ''
			[943] link '\ue606'
				StaticText '\ue606'
			StaticText 'Copyright © 2025 Magento Commerce Inc. All rights reserved.'
		[945] paragraph ''
			[946] strong ''
				StaticText 'Magento'
			StaticText 'ver. 2.4.6'
		[947] link 'Privacy Policy'
		StaticText '|'
		[948] link 'Account Activity'
		StaticText '|'
		[949] link 'Report an Issue'

"""
prompt_templates = PromptTemplates(
    system_prompt=SYS_PROMPT,
)

with ToolCollection.from_mcp({"url": "http://localhost:8931/sse"}, trust_remote_code=True) as tool_collection:
    print(tool_collection.tools)
    agent = CodeAgent(tools=[*tool_collection.tools], model = model, add_base_tools=False)
    question = "What are the top-3 best-selling product in Jan 2023"
    agent.run(question + FIRST_PAGE)